#!/usr/bin/env bash
# Deploys site/ to S3 under the "site/" prefix. Run this after
# `python scripts/tf.py apply`, or any time you've only changed the
# frontend and don't need a full apply.
#
# site/ is copied into build/site/ and deployed from there, with the real
# config.js (Cognito/CloudFront values) written over the placeholder copy.
# build/ is gitignored and the committed site/config.js is never touched, so
# a deploy never leaves deployment values in the working tree.
#
# Usage: scripts/deploy_site.sh
set -euo pipefail
cd "$(dirname "$0")/.."

if [ ! -f .env ]; then
  echo "Missing .env -- copy env.example to .env at the repo root and fill it in." >&2
  exit 1
fi
set -a
source .env   # S3_BUCKET / AWS_REGION / AWS_PROFILE / DOMAIN_NAME -- see env.example
set +a

for var in S3_BUCKET AWS_REGION AWS_PROFILE; do
  if [ -z "${!var:-}" ]; then
    echo "Missing $var in .env -- see env.example." >&2
    exit 1
  fi
done

rm -rf build/site
mkdir -p build/site
# The local preview artefacts and the folder's own README are not deployed.
tar -cf - --exclude=manifest.json --exclude=sample-photos --exclude=README.md -C site . | tar -xf - -C build/site

DOMAIN=$(python scripts/tf.py output -raw site_domain)
COGNITO_DOMAIN=$(python scripts/tf.py output -raw cognito_hosted_ui_domain)
COGNITO_CLIENT_ID=$(python scripts/tf.py output -raw cognito_client_id)
DISTRIBUTION_ID=$(python scripts/tf.py output -raw cloudfront_distribution_id)

cat > build/site/config.js << CONFIGEOF
// GENERATED by scripts/deploy_site.sh into the gitignored build/ directory.
// This is NOT the committed site/config.js -- do not hand-edit, and do not
// copy it back into site/.
export const MANIFEST_URL = "/photos/manifest.json";
export const COGNITO_DOMAIN = "${COGNITO_DOMAIN}";
export const COGNITO_CLIENT_ID = "${COGNITO_CLIENT_ID}";
export const REDIRECT_URI = "https://${DOMAIN}/auth/callback";
CONFIGEOF

aws s3 sync build/site/ "s3://${S3_BUCKET}/site/" \
  --profile "${AWS_PROFILE}" --region "${AWS_REGION}" --delete

aws cloudfront create-invalidation \
  --distribution-id "${DISTRIBUTION_ID}" --paths "/*" \
  --profile "${AWS_PROFILE}"

echo "Deployed to https://${DOMAIN}/"
